CREATE DATABASE hotel_nu4;
USE hotel_nu4;
CREATE TABLE Guests (
    NationalID INT PRIMARY KEY,
    FirstName VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
    LastName VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
    Email VARCHAR(100) CHARACTER SET UTF8MB4 UNIQUE NOT NULL,
    PhoneNumber VARCHAR(15),
    CheckInDate DATE NOT NULL
);

CREATE TABLE HotelReviews (
    ReviewID INT PRIMARY KEY AUTO_INCREMENT,
    NationalID INT NOT NULL,
    ReviewDate DATE NOT NULL,
    Rating INT CHECK (Rating BETWEEN 1 AND 5),
    Comments TEXT CHARACTER SET UTF8MB4,
    FOREIGN KEY (NationalID) REFERENCES Guests(NationalID) ON DELETE CASCADE
);

CREATE TABLE Suites (
    Suite_ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    Description TEXT CHARACTER SET UTF8MB4,
    RoomSize DECIMAL(10, 2),
    NumberOfRooms INT,
    Capacity INT,
    PricePerNight DECIMAL(10, 2) NOT NULL,
    AvailabilityStatus VARCHAR(50) CHARACTER SET UTF8MB4 DEFAULT 'Available',
    ViewType VARCHAR(100) CHARACTER SET UTF8MB4
);

CREATE TABLE Restaurants (
    Restaurant_ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) CHARACTER SET UTF8MB4 NOT NULL,
    CuisineType VARCHAR(100) CHARACTER SET UTF8MB4 NOT NULL,
    OpeningHours VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
    SeatingCapacity INT NOT NULL,
    Menu TEXT CHARACTER SET UTF8MB4,
    Specialties TEXT CHARACTER SET UTF8MB4,
    ReservationRequired BOOLEAN DEFAULT FALSE,
    ContactNumber VARCHAR(15),
    AveragePricePerPerson DECIMAL(10, 2),
    IndoorOutdoorSeating VARCHAR(50) CHARACTER SET UTF8MB4,
    Status VARCHAR(50) CHARACTER SET UTF8MB4 DEFAULT 'Open',
    Services TEXT CHARACTER SET UTF8MB4
);

CREATE TABLE Reception (
    ReceptionID INT PRIMARY KEY,
    FirstName VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
    LastName VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
    Email VARCHAR(100) CHARACTER SET UTF8MB4 NOT NULL,
    Phone VARCHAR(15) NOT NULL,
    Rate INT
);

CREATE TABLE RShifts (
    RShiftID INT PRIMARY KEY,
    ReceptionID INT NOT NULL,
    ShiftDate DATE NOT NULL,
    ShiftType VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
    FOREIGN KEY (ReceptionID) REFERENCES Reception(ReceptionID)
);

CREATE TABLE RTasks (
    RTaskID INT PRIMARY KEY AUTO_INCREMENT,
    ReceptionID INT NOT NULL,
    TaskDescription VARCHAR(300) CHARACTER SET UTF8MB4 NOT NULL,
    TaskDate DATE NOT NULL,
    CompletionStatus VARCHAR(20) CHARACTER SET UTF8MB4 DEFAULT 'Pending',
    FOREIGN KEY (ReceptionID) REFERENCES Reception(ReceptionID)
);

CREATE TABLE Cleaning (
    CID INT PRIMARY KEY,
    FirstName VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
    LastName VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
    Email VARCHAR(100) CHARACTER SET UTF8MB4 NOT NULL,
    Phone VARCHAR(15) NOT NULL
);

CREATE TABLE RoomTypes (
    TypeName VARCHAR(50) PRIMARY KEY,
    BasePrice DECIMAL(10, 2) NOT NULL,
    Description TEXT CHARACTER SET UTF8MB4
);

CREATE TABLE Rooms (
    RoomID INT AUTO_INCREMENT PRIMARY KEY,
    RoomNumber VARCHAR(10) UNIQUE NOT NULL,
    RoomType VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
    Capacity INT NOT NULL,
    PricePerNight DECIMAL(10, 2) NOT NULL,
    AvailabilityStatus ENUM('available', 'occupied', 'maintenance') CHARACTER SET UTF8MB4 NOT NULL,
    Description TEXT CHARACTER SET UTF8MB4,
    FOREIGN KEY (RoomType) REFERENCES RoomTypes(TypeName)
);

CREATE TABLE Bookings (
    BookingID INT AUTO_INCREMENT PRIMARY KEY,
    RoomID INT NOT NULL,
    CustomerID INT NOT NULL,
    CheckInDate DATE NOT NULL,
    CheckOutDate DATE NOT NULL,
    TotalPrice DECIMAL(10, 2) NOT NULL,
    BookingStatus ENUM('confirmed', 'checked-in', 'cancelled') CHARACTER SET UTF8MB4 NOT NULL,
    FOREIGN KEY (RoomID) REFERENCES Rooms(RoomID)
);
